import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="App">
          <header>
            <ul>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/table">CSS Table</Link>
              </li>
              <li>
                <Link href="/tableHover">CSS Table Hover</Link>
              </li>
              <li>
                <Link href="/tableEmitter">CSS Table Event Emitter</Link>
              </li>
              <li>
                <Link href="/grid">CSS Grid</Link>
              </li>
              <li>
                <Link href="/gridHover">CSS Grid Hover</Link>
              </li>
            </ul>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
